import "./globals.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  author: "Danilo",
  keywords: "React"
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-br'>
      <body>
        <Header/>        
        {children}</body>
    </html>
  );
}
